### PR TITLE
add support to basic auth, closes #8

### LINKED ISSUE #8: Support Basic Authentication
Support Basic Authentication when the Presto end-point is configured for LDAP Authentication.

### PR DESCRIPTION
**Pull request by felipejfc**
This is a simple PR that adds support to basicauth on http[s].

Closes issue #8

### CODE REVIEW

**Comment by electrum** [comment]
We should only allow basic auth if HTTPS is enabled. Otherwise, the password will be sent in the clear.

**Comment by fiorix** [comment]
Ping @felipejfc 

Any word here?

**Comment by felipejfc** [comment]
hi @fiorix, sorry for the delay, I was too busy with work stuff, I just pushed the modifications to the code, tell me if it's ok for you now.

**Comment by fiorix** [comment]
👍 

Valeu!

**Pull request merged**
